class_name ConstData
const DIR_TO_RELATIVE_SWORD_POS = {
	ENUMS.DIRECTION.RIGHT: Vector2(-56, 56), 
	ENUMS.DIRECTION.LEFT: Vector2(8, 56)}

const HELD_ITEM_TO_COLLISION_LAYER = {
	ENUMS.HELD_ITEM.NONE: ENUMS.COLLISION_LAYER.NONE,
	ENUMS.HELD_ITEM.SWORD_1: ENUMS.COLLISION_LAYER.SWORD_1,
	ENUMS.HELD_ITEM.SWORD_2: ENUMS.COLLISION_LAYER.SWORD_2}

const SWORDSMAN_TO_COLLISION_LAYER = {
	ENUMS.SWORDSMAN.BLACK: ENUMS.COLLISION_LAYER.BLACK,
	ENUMS.SWORDSMAN.BLUE: ENUMS.COLLISION_LAYER.BLUE}
