enum DIRECTION {LEFT, RIGHT}
enum SWORD_STATE {GROUNDED, THROWN, HELD}
enum HELD_ITEM {NONE, SWORD_1, SWORD_2}
enum SWORDSMAN {BLACK, BLUE}
enum COLLISION_LAYER {NONE, FLOOR, SWORDSMAN, SWORD_1, SWORD_2}
